import json
from pydantic import BaseModel, Field
from typing import List
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.output_parsers import PydanticOutputParser
from watchtower.core.state import AgentState
from watchtower.agents.planner import get_llm

class IDORReasoningOutput(BaseModel):
    confidence_score: int = Field(description="Confidence score from 1-10 that IDOR vulnerabilities exist here.", ge=1, le=10)
    potential_business_impact: str = Field(description="The potential business impact if these endpoints contain IDOR vulnerabilities.")
    testing_plan: List[str] = Field(description="A comprehensive step-by-step token/UserID swapping testing plan.")

def logic_analysis_node(state: AgentState) -> dict:
    observations = state.get("observations", [])
    if not observations:
        return {"messages": ["No observations found for logic analysis."]}
        
    # Gather output from recent tools, especially web recon tools like httpx, kiterunner, arjun
    recon_data = "\n".join(
        f"Tool: {obs.get('tool')}\nOutput: {obs.get('output')}"
        for obs in observations if obs.get("tool") in ["httpx", "kiterunner", "arjun", "gobuster", "ffuf"]
    )
    
    parser = PydanticOutputParser(pydantic_object=IDORReasoningOutput)
    
    prompt = f"""
You are a Senior Security Researcher specializing in Insecure Direct Object Reference (IDOR) and business logic flaws.
Review the following web recon endpoints and parameters discovered on the target.

Web Recon Data:
{recon_data}

Analyze the data for potential IDOR vulnerabilities. Generate a strict JSON output matching the expected schema.
Assess the likelihood of IDOR, describe the potential business impact, and provide a detailed step-by-step methodology to test for token and UserID swapping.
{parser.get_format_instructions()}
"""
    
    try:
        llm = get_llm()
        chain = llm | parser
        result = chain.invoke([HumanMessage(content=prompt)])
        
        finding = {
            "title": "IDOR Logic Analysis Plan",
            "severity": "Info",
            "description": f"Confidence: {result.confidence_score}/10\nImpact: {result.potential_business_impact}\nPlan: {', '.join(result.testing_plan)}",
            "evidence": "Generated by Logic Analysis Agent"
        }
        return {"findings": [finding]}
    except Exception as e:
        return {"messages": [f"Logic analysis error: {e}"]}
